cache:
  paths:
  - vendor/

image: edbizarro/gitlab-ci-pipeline-php:8.0-alpine

test:
  script:
    - composer install --no-progress --no-interaction --prefer-dist
    - php vendor/bin/phpunit --coverage-text --colors=never
