cache:
  paths:
  - vendor/

test:
  image: poldixd/laravel:latest
  script:
    - composer install --no-progress --no-interaction --prefer-dist
    - php vendor/bin/phpunit --coverage-text --colors=never
